### ISSUE TITLE
Issue on access website

### ISSUE THREAD

**Issue by egen155** [biztransit/techsupport#17]
![WhatsApp Image 2023-08-04 at 10 24 44 AM](https://github.com/biztransit/techsupport/assets/141385297/040a31f9-712c-43ab-a9e9-69c3c3d755b5)

New client can't access to website, show [threat found]

**Comment by hiqsociety** [comment]
@egen155 we have already performed hours long multiple system scans and online security malware scan which doesnt show this issue.

**google has malware detection too. if your site has issue, ur ranking will drop and will show site has malware.**

**currently your website is ranked first page and first for most keywords related to your business.**

**this issue is unwarranted and false**. please check the integrity of your device on your side.

**Comment by kolinfluence** [comment]
closing this issue as resolved by client.
